In [66]:
import pandas as pd
import re

In [22]:
path = f'C:/Users/Angelo/Documents/github/capstone_project/data/raw/raw_data.csv'

In [ ]:
def load_data(path):
    df = pd.read_csv(path)
    return df

In [27]:
def copy_data(df):
    df_copy = df.copy()
    return df_copy

In [28]:
df = copy_data(load_data(path))

In [30]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

# check value range

In [ ]:
df.describe(include='all')
# df['Ticket'].unique() # drop
# df['Cabin'].value_counts() # Parse out first cabin, split letter and number

def get_first_cabin_in_a_row(cabin: str):
    # Handle None or empty strings
    if pd.isna(cabin) or cabin.strip() == '':
        return pd.Series(['', ''])  # Returning empty strings for letter and number
    
    # Split the cabins by space and take the first one
    first_cabin = cabin.split(' ')[0]
    
    # Validate that first_cabin fits (letters)(numbers) groups
    match = re.match(r'([A-Za-z]+)(\d+)', first_cabin)
    
    if match:
        # Save match groups to respective vars
        cabin_letter, cabin_number = match.groups()
        return pd.Series([cabin_letter, cabin_number])
    
    return pd.Series(['', ''])  # Return empty strings if no match found

# Apply the function to the 'Cabin' column and create new columns
df[['cabin_letter', 'cabin_number']] = df['Cabin'].apply(get_first_cabin_in_a_row) # ✅

# df['Embarked'].head()

   cabin_letter cabin_number
0
1
2
3
4
5
6
7
8
9
10
11
12            B           45
13
14            E           31

# address missing data

In [ ]:
# drop

Cabin
B57 B59 B63 B66    3
B45                2
C78                2
C31                2
C23 C25 C27        2
                  ..
B41                1
C7                 1
D40                1
D38                1
C105               1
Name: count, Length: 76, dtype: int64

In [ ]:
cols_with_missing_values = df.columns[df.isnull().any()].tolist()

TypeError: IndexOpsMixin.tolist() missing 1 required positional argument: 'self'